### ISSUE TITLE
url encoding problem

### ISSUE THREAD

**Issue by michaelbilow** [debrouwere/facebook-insights#4]
Hi, I ran into the following error when executing:

```
page.insights.daily(['page_impressions', 'page_fan_adds']).range(months=1).get()
...
  File ".../site-packages/facebookinsights/utils/api.py", line 32, in _resolve_endpoint
    qs = url.encode({key: value for key, value in options.items() if key not in blacklist})
TypeError: encode() argument 1 must be string, not dict`
```

I resolved this by adding in `import urllib` at the top of the api.py file and changing that line to urllib.urlencode(...).

**Comment by debrouwere** [comment]
Thanks for reporting, turned out to be a stupid mistake where `url` was both a local variable and an imported utility library, one overwriting the other. Should be fixed in master and the latest version (0.3.4) on PyPI.
