### ISSUE TITLE
KeyError: 'username' with README.md Examples

### ISSUE THREAD

**Issue by davidmann4** [debrouwere/facebook-insights#6]
getting the following error:

 File "/usr/local/lib/python2.7/dist-packages/facebookinsights/graph.py", line 366, in **init**
    self.username = data['username']

maybe use 'name' instead?

**Comment by davidmann4** [comment]
removed that line and it worked

**Comment by MoorsTech** [comment]
Just ran into the same Issue, no idea why that line would be there in the first place, this should've never worked O.o

**Comment by davidmann4** [comment]
created a pull request https://github.com/debrouwere/facebook-insights/pull/7

**Comment by jercole** [comment]
This used to work in old versions. I Think it stopped working with 2.5. 

You're going to find there's quite a bit more than that that requires changing eventually.

**Comment by davidmann4** [comment]
well someone accepted my pull request anyways so we can close this issue
